GET http://localhost:5000/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImZhd2Fsczk4QGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzQyOTE3MDEyLCJleHAiOjE3NDI5MjA2MTJ9.Vb92xZ0bVdU8xXcd_ISto59nlC-j5ZTlpssx5mz8Zco

###
GET http://localhost:5000/cities HTTP/1.1

###
GET http://localhost:5000/types HTTP/1.1

###
GET http://localhost:5000/hotels HTTP/1.1

###
GET http://localhost:5000/hotel/6311a9c64a642f01423490bf HTTP/1.1

###
POST http://localhost:5000/search-hotels HTTP/1.1
Content-Type: application/json

{
    "city" : "Ha Noi",
    "roomsTotal": "3"
}

###
POST http://localhost:5000/check-availability-rooms HTTP/1.1
Content-Type: application/json

{
    "hotelId":"6311a9c64a642f01423490bf",   
    "dateStart": "2025-04-09T07:40:37.890Z",
    "dateEnd": "2025-04-09T08:20:37.890Z"
}

###
POST http://localhost:5000/add-transaction HTTP/1.1
Content-Type: application/json

{
    "user": "tienvn998@gmail.com",
    "rooms": [{
        "roomId": "6310e01a8cfecfd90b30ca30",
        "roomNumbers": ["123","321","113"]
    }],
    "hotelId":"6311a9c64a642f01423490bf",
    "dateStart": "2025-04-09T07:40:37.890Z",
    "dateEnd": "2025-04-09T08:20:37.890Z",
    "price":1000, 
    "payment":"Credit"
}
