###
Get http://localhost:5000/get-users-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUxMTgxMDYsImV4cCI6MTc0NTEyMTcwNn0.dtmkeTUdtLe-o-xMIoixB5xLglZKv_LVRn_XOcN62fw

###
Get http://localhost:5000/get-transactions-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUxMTgxMDYsImV4cCI6MTc0NTEyMTcwNn0.dtmkeTUdtLe-o-xMIoixB5xLglZKv_LVRn_XOcN62fw

###
Get http://localhost:5000/get-revenue-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUxMTgxMDYsImV4cCI6MTc0NTEyMTcwNn0.dtmkeTUdtLe-o-xMIoixB5xLglZKv_LVRn_XOcN62fw

###
Get http://localhost:5000/get-balance HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUxMTgxMDYsImV4cCI6MTc0NTEyMTcwNn0.dtmkeTUdtLe-o-xMIoixB5xLglZKv_LVRn_XOcN62fw

###
Get http://localhost:5000/last-transactions HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUxMTgxMDYsImV4cCI6MTc0NTEyMTcwNn0.dtmkeTUdtLe-o-xMIoixB5xLglZKv_LVRn_XOcN62fw
