###
Get http://localhost:5000/get-users-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODAzOTM1ZTRiY2RkZWM0NTIxODdjNzYiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUwNzA3MzYsImV4cCI6MTc0NTA3NDMzNn0.PtPz1-vxl3T8qMUwjf4llzWN-x43r93jWINIsqMKHjI

###
Get http://localhost:5000/get-transactions-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODAzOTM1ZTRiY2RkZWM0NTIxODdjNzYiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUwNzA3MzYsImV4cCI6MTc0NTA3NDMzNn0.PtPz1-vxl3T8qMUwjf4llzWN-x43r93jWINIsqMKHjI
